# Generated by Django 5.0.6 on 2024-05-28 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('_club', '0001_initial'),
        ('_member', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='president',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='_member.student'),
        ),
    ]
