# Generated by Django 5.0.6 on 2024-06-10 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_club', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='description',
            field=models.TextField(max_length=200),
        ),
    ]
