# Generated by Django 5.0.6 on 2024-06-11 09:38

import _club.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_club', '0004_club_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=_club.models.upload_image),
        ),
    ]
