# Generated by Django 5.0.6 on 2024-06-10 12:51

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_club', '0003_alter_club_description'),
        ('_faculty', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='mobile',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+919886051590', max_length=128, region=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='faculty',
            name='clubs',
            field=models.ManyToManyField(max_length=3, to='_club.club'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='department',
            field=models.CharField(max_length=10),
        ),
    ]
