# Generated by Django 5.0.6 on 2024-06-10 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_club', '0003_alter_club_description'),
        ('_faculty', '0002_faculty_mobile_alter_faculty_clubs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='clubs',
            field=models.ManyToManyField(to='_club.club'),
        ),
    ]
