# Generated by Django 5.0.6 on 2024-06-11 16:45

import _faculty.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_faculty', '0003_alter_faculty_clubs'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=_faculty.models.upload_image),
        ),
    ]
