# Generated by Django 5.0.6 on 2024-06-10 12:51

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('_member', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='mobile',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+919886051590', max_length=128, region=None),
            preserve_default=False,
        ),
    ]
