# Generated by Django 5.0.6 on 2024-06-11 15:30

import _member.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_member', '0003_student_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=_member.models.upload_image),
        ),
    ]
