# Generated by Django 5.0.6 on 2024-06-10 12:37

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('_event', '0002_alter_event_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='mobile',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+91 9886051590', max_length=128, region=None),
            preserve_default=False,
        ),
    ]
